# Generated by Django 4.1.13 on 2025-11-14 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pki', '0002_certificate_p12_bundle'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='certificate',
            name='pki_cert_hash_idx',
        ),
        migrations.RenameIndex(
            model_name='certificate',
            new_name='pki_certifi_serial__c0da20_idx',
            old_name='pki_certifi_serial__idx',
        ),
        migrations.RenameIndex(
            model_name='certificate',
            new_name='pki_certifi_user_id_92804a_idx',
            old_name='pki_certifi_user_re_idx',
        ),
        migrations.RenameIndex(
            model_name='certificate',
            new_name='pki_certifi_not_aft_322adf_idx',
            old_name='pki_certifi_not_aft_idx',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='certificate_hash',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='p12_bundle',
        ),
    ]
