# Generated by Django 4.1.13 on 2025-11-18 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('archived', 'Archived'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blockchain_tx_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('blockchain_block', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigations_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blockchain_investigation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'blockchain_tag',
            },
        ),
        migrations.CreateModel(
            name='InvestigationNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='blockchain.investigation')),
            ],
            options={
                'db_table': 'blockchain_investigation_note',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestigationActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='blockchain.investigation')),
            ],
            options={
                'db_table': 'blockchain_investigation_activity',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GUIDMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guid', models.UUIDField(db_index=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investigator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guid_mappings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blockchain_guid_mapping',
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file_hash', models.CharField(max_length=64)),
                ('file_size', models.BigIntegerField()),
                ('ipfs_hash', models.CharField(blank=True, max_length=100, null=True)),
                ('ipfs_uploaded', models.BooleanField(default=False)),
                ('blockchain_tx_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('blockchain_block', models.IntegerField(blank=True, null=True)),
                ('uploaded_anonymously', models.BooleanField(default=False)),
                ('anonymous_guid', models.UUIDField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='blockchain.investigation')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blockchain_evidence',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='BlockchainTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tx_hash', models.CharField(max_length=66, unique=True)),
                ('block_number', models.IntegerField()),
                ('tx_type', models.CharField(max_length=50)),
                ('data', models.JSONField()),
                ('user_guid', models.UUIDField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blockchain_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blockchain_transaction',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='InvestigationTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockchain.investigation')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockchain.tag')),
            ],
            options={
                'db_table': 'blockchain_investigation_tag',
                'unique_together': {('investigation', 'tag')},
            },
        ),
    ]
