# Generated by Django 4.1.13 on 2025-11-14 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_fix_superuser_field_defaults'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
    ]
